### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'eosjs_key_conversions_1.PrivateKey.fromString')

### ISSUE THREAD

**Issue by ekkis** [EOSIO/eosjs#713] opened 2020-04-06 18:47 UTC
**Version of EOSJS**
I have installed a version packaged into RPM 2 hours ago:
```bash
# npm i -S eosjs@21.0.0-a6ad012.0
```

**Describe the bug**
It produces the error described above at line 86 of eosjs-jssig.js

**To Reproduce**
```js
const {JsSignatureProvider} = require('eosjs/dist/eosjs-jssig');  // development only
var x = new JsSignatureProvider([privKey])
```

**Analysis**
the `eosjs-key-conversions.ts` file contains something like:
```js
import { PrivateKey } from './PrivateKey';
export { PrivateKey } from './PrivateKey';
```
which produces something like this (in `eosjs-key-conversions.js`):
```js
var PrivateKey_2 = require("./PrivateKey");
exports.PrivateKey = PrivateKey_2.PrivateKey; # this dereference produces undefined
```
but `eosjs-jssig.js` attempts to use it like this:
```js
var eosjs_key_conversions_1 = require("./eosjs-key-conversions");
var priv = eosjs_key_conversions_1.PrivateKey.fromString(k);
```
where it fails because there is no `PrivateKey` member of `eosjs_key_conversions_1`.  the reason is that `PrivateKey.js` exports a function, which doesn't declare a member of that name, so one way to fix this is to make the reference properly:
```js
exports.PrivateKey = PrivateKey_2;
```
but since this is generated code, we can't do it.  the other way would be to return an object with the proper key name from `PrivateKey.js`, which declares and returns a function:
```js
function PrivateKey(key, ec) {
        this.key = key;
        this.ec = ec;
    }
return PrivateKey
```
so this would need to be fixed like this:
```js
return { PrivateKey }
```
but such a fix would break anyone calling context expecting to receive a function when sourcing this file.  such contexts would now need to do:
```js
const {PrivateKey} = require('./PrivateKey.js')
```
I'm not sure what the right fix is

**Comment by jlamarr22** [comment] 2020-04-06 19:45
I'm not seeing an error when running the following:
```
const eosjs = require('eosjs');
const { generateKeyPair } = require('eosjs/dist/eosjs-key-conversions');
const { PrivateKey } = require('eosjs/dist/PrivateKey');
const { JsSignatureProvider } = require('eosjs/dist/eosjs-jssig');

const keyPair = generateKeyPair(eosjs.Numeric.KeyType.k1);
const privateKeyString = keyPair.privateKey.toString();
const publicKeyString = keyPair.publicKey.toString();

console.log(`PrivateKey: ${privateKeyString}\nPublicKey: ${publicKeyString}`);

const provider = new JsSignatureProvider([privateKeyString]);
```

EOSJS version: `21.0.0-45854c1.0`

> var x = new JsSignatureProvider([privKey])

Your issue occurs here? Can you show me some more code?

**Comment by ekkis** [comment] 2020-04-06 20:07
interestingly, I don't get this error running the code in Node.  I get it in React Native

**Comment by ekkis** [comment] 2020-04-06 21:41
as a matter of interest, I've expounded on the issue here: https://stackoverflow.com/questions/61068858/require-works-in-node-but-fails-in-react-native

**Comment by jlamarr22** [comment] 2020-04-06 22:56
> interestingly, I don't get this error running the code in Node. I get it in React Native

Can you create a minimal reproduction of this issue in React Native using something like Expo/Snack?

**Comment by ekkis** [comment] 2020-04-06 22:58
I was thinking to do that.  stand by, will notify here

**Comment by ekkis** [comment] 2020-04-07 22:28
here's a snack that we can use to work on this: https://snack.expo.io/@ekkis/thoughtful-ice-cream you will notice that if you run on iOS you'll get the error: "secure random generation not supported by this browser use chrome, FireFox or Internet Explorer 11", which is a message issued by eosjs 20.0.0, not v21

in my local environment this message disappeared once I upgraded to 21 so I'm not sure why it appears here since, as you can see from the `package.json`, I've included ^21.0.0-a6ad012.0

**Comment by ekkis** [comment] 2020-04-07 22:29
you will notice that if I run the snack on Web, there is no error

**Comment by jlamarr22** [comment] 2020-04-08 16:59
Thanks for the example!

I've never seen a dependency's single file resolved in that way, but maybe it works properly for expo because of something going on behind the scenes (I tested it locally and it does not work). In your example, `"eosjs/dist/eosjs-jssig": "latest"` looks like it's going to correspond to NPM's latest package, which is version 20.0.3, so when you say:
```
"eosjs": "^21.0.0-a6ad012.0",
"eosjs/dist/eosjs-jssig": "latest"
```
you're essentially pulling the entire package for eosjs with the edge version and then resolving the `eosjs-jssig` file as latest, so two completely different versions. That's why you're seeing the error you mention above. Specifically, this error seems to be coming from https://github.com/EOSIO/eosjs-ecc/blob/master/package.json#L48. We swapped out eosjs-ecc with elliptic in v21, so we moved it to a devDependency for integration testing purposes, which is why you don't see this error in v21.

If you change it to: `"eosjs/dist/eosjs-jssig": "21.0.0-a6ad012.0"`, then expo correctly pulls version 21 for that file instead and it can be resolved properly. Check out https://snack.expo.io/@jlamarr22/7cf938

**Comment by ekkis** [comment] 2020-04-09 17:47
thank you.  I actually came across eosjs-rn (it was suggested to me on the Telegram group), which  has been tested on React Native and I can confirm it works well.  so I'm moving on from this but will leave the issue open so maintainers can close with WONTFIX or address the issue

thanks for looking into this.  I burnt a few days with it

**Comment by jlamarr22** [comment] 2020-04-09 20:57
There is a problem using EOSJS v20 with React Native that stems from `eosjs-ecc`'s dependency not being compatible with React Native: https://github.com/EOSIO/eosjs-ecc/blob/master/package.json#L48. 

I am closing this issue due to the underlying problem stemming from a dependency that will eventually be deprecated, an existing/working solution for v20 (https://github.com/Game-X-Coin/eosjs-rn), and the fact that we have confirmed in v21 via PoCs above that this is no longer an issue. 

If using React Native:
- If you absolutely need EOSJS v20, use https://github.com/Game-X-Coin/eosjs-rn
- Otherwise, upgrade to EOSJS v21 (full release coming soon)

**Closed by jlamarr22** 2020-04-09 20:57 UTC
